### ISSUE TITLE
Filling the Repository Research Page

### ISSUE THREAD

**Issue by yusuferdemnacar** [bounswe/bounswe2022group6#12]
The repository research page must be filled in as everyone needs to discover a repository. Please edit the [repository research](https://github.com/bounswe/bounswe2022group6/wiki/Repository-Research) page accordingly when you find a repository that you like. A small paragraph explaining what the repository is for and why you liked it would be nice.

Please tick your name when you are done.

- [x] Ali Kaan
- [x] Artun
- [x] Hakan
- [x] Yasir
- [x] Alp Eren
- [x] Aral
- [x] Berk
- [x] Bedirhan
- [x] Berfin
- [x] Hatice
- [x] İrem
- [x] Yusuf Erdem

**Dealine:** 07.03.2022

**Comment by LehabuL** [comment]
@iremmer @aeren02  Can you please finalize your part so that we can close this issue, please?

**Comment by iremmer** [comment]
Maybe it is better to tag beforehand, I've just seen this issue.
