### ISSUE TITLE
Practice App: Fixing Tests for Article App

### ISSUE THREAD

**Issue by Aliqaan** [bounswe/bounswe2022group6#126]
According to feedback given by my teammates, I noticed that some of the tests in article app was using the post app's url with the same name. This needs to be fixed and to avoid same kind of mistakes tests and urls of article app should be arranged.

**Comment by Aliqaan** [comment]
I have modified the code slightly so that the tests are running as expected now. You can see the details [here](https://github.com/bounswe/bounswe2022group6/commit/a14cbb784bc0c8a62a7406ba576eaf042af9a08a).

**Comment by yusuferdemnacar** [comment]
The changes are OK.
