### ISSUE TITLE
Practice App: Design

### ISSUE THREAD

**Issue by haticerk** [bounswe/bounswe2022group6#141]
As a part of practice-app implementation, we need to create use-case, class and sequence diagrams. Since we implemented separate functionalities, it is an individual task for everyone. An online document is shared to work together.  Please update the list below when you completed your part.

**Use-Case Diagram**
- [x] Artun Akdoğan 
- [x] Hakan Balık
- [x] Ali Kaan Biber
- [x] Yasir Dikbaş
- [x] Aral Dörtoğul
- [x] Hatice Erk
- [ ] Alp Eren İnceoğlu
- [x] Yusuf Erdem Nacar
- [x] Ramazan Bedirhan Pamukçuoğlu
- [x] Berfin Şimşek 
- [ ] Mustafa Berk Turgut
- [x] Beyza İrem Urhan

**Class Diagram**
- [x] Artun Akdoğan 
- [x] Hakan Balık
- [x] Ali Kaan Biber
- [x] Yasir Dikbaş
- [x] Aral Dörtoğul
- [x] Hatice Erk
- [ ] Alp Eren İnceoğlu
- [x] Yusuf Erdem Nacar
- [x] Ramazan Bedirhan Pamukçuoğlu
- [x] Berfin Şimşek 
- [ ] Mustafa Berk Turgut
- [x] Beyza İrem Urhan

**Sequence Diagram**
- [x] Artun Akdoğan 
- [x] Hakan Balık
- [x] Ali Kaan Biber
- [ ] Yasir Dikbaş
- [x] Aral Dörtoğul
- [x] Hatice Erk
- [ ] Alp Eren İnceoğlu
- [x] Yusuf Erdem Nacar
- [x] Ramazan Bedirhan Pamukçuoğlu
- [x] Berfin Şimşek 
- [ ] Mustafa Berk Turgut
- [x] Beyza İrem Urhan

**Deadline: 19.05.2022**

**Comment by yusuferdemnacar** [comment]
I added the diagrams for Advice App to the shared Lucidchart project.
