### ISSUE TITLE
Milestone 2: Writing the Executive Summary

### ISSUE THREAD

**Issue by yusuferdemnacar** [bounswe/bounswe2022group6#144]
The executive summary for the Milestone 2 Group report should be written. The subtitles for the executive summary are:

- Summary of project and overall status
- URL of the deployed application
- API URL
- Basic functionality of the project
  - [x]  Advice
  - [x] Location Manager
  - [x] Article
  - [x] Post
  - [x] News
  - [x] User
  - [x] Coronavirus
  - [x] Drug Side Effects
  - [x] Comment

- Challenges we met as a group
- List the status of deliverables.

**Deadline:** 19.05.2022

**Comment by BPamukcuoglu** [comment]
I have written the basic functionalities and the requirements of Drugs and Side Effects App in Milestone 2 report.

**Comment by haticerk** [comment]
In the Milestone 2 report, I have written the basic functionalities and requirements of User API.

**Comment by Aliqaan** [comment]
Basic functionalities and the requirements of Article API are written in the Milestone 2 report.

**Comment by iremmer** [comment]
I have written the basic functionalities and the requirements of Coronavirus API in the Milestone 2 report.

**Comment by yasirdikbas** [comment]
I have written the basic functionalities and the requirements of Hospital API
