### ISSUE TITLE
Milestone 2 Report: Project Plan

### ISSUE THREAD

**Issue by haticerk** [bounswe/bounswe2022group6#148]
As a part of milestone 2 report, the project plan should be updated and added to report docs.

**Deadline: 19.05.2022**

**Comment by haticerk** [comment]
I updated the project plan, @berfinsimsekk please review and add the plan to docs

**Comment by berfinsimsekk** [comment]
I have reviewed the plan and deleted the part before milestone 1 and after milestone 2 after discussing with other team members. I have created the pdf file, we will merge it after finishing docs.
