### ISSUE TITLE
Uploading Meeting 17 Notes

### ISSUE THREAD

**Issue by iremmer** [bounswe/bounswe2022group6#149]
I will upload the meeting notes that we had on 05.18.2022.

**Comment by iremmer** [comment]
I uploaded the corresponding meeting notes, you can see them [here.](https://github.com/bounswe/bounswe2022group6/wiki/Meeting-%2317---05.18.2022)

**Comment by yusuferdemnacar** [comment]
I added the [page](https://github.com/bounswe/bounswe2022group6/wiki/Meeting-%2317---05.18.2022) to the sidebar. Thanks, for the notes.
