### ISSUE TITLE
Creating a personal Wiki page for İhsan Mert Atalay

### ISSUE THREAD

**Issue by mberkturgut** [bounswe/bounswe2022group6#159]
A Wiki containing sections including but not limited to

- About me 
- Contact info
- A template for weekly efforts

should be created. 

Wiki pages of other members can be used as an example.

After completion, links in the team member section of the home page and the sidebar will be updated accordingly.

Due: 10 Oct 2022

**Comment by ihsanmertatalay** [comment]
I published my wiki page and changed link at the home page of wiki

**Comment by ihsanmertatalay** [comment]
I published my wiki page and changed link at the home page of wiki
