### ISSUE TITLE
Doing research about privacy policy

### ISSUE THREAD

**Issue by iremmer** [bounswe/bounswe2022group6#16]
In our second assignment, _Medical Experience Sharing Platform_, we get some information from users, so we need to know about the privacy policy.
Here is the regarding part in the description:

- "Ethical concerns must be considered, such as protection of personal information, contact information, adherence to copyrights, licensing considerations. You must follow the rules defined by GDPR/KVKK while implementing the project. Compliance with doctors’ advice is paramount."

You can add your notes to this [page](https://github.com/bounswe/bounswe2022group6/wiki/Privacy-Policy):

**Comment by mberkturgut** [comment]
@iremmer looking good! Thanks for your detailed work.

**Comment by yusuferdemnacar** [comment]
Reminder.

**Comment by mberkturgut** [comment]
Decided as the team to be closed for now, will be updated as necessary
