### ISSUE TITLE
Revising the Wiki

### ISSUE THREAD

**Issue by yusuferdemnacar** [bounswe/bounswe2022group6#160]
The project repository and the wiki should be revised.
The following parts should be reviewed and updated if necessary.
- README.md
- Wiki
  - Personal Pages
  - Deliverables
  - Meeting Notes

**Deadline:** 11.10.2022

**Comment by berfinsimsekk** [comment]
I updated the wiki's title as "CMPE352/451 2022 - Group 6 Wiki" and added İhsan's name.

**Comment by berfinsimsekk** [comment]
I added Milestone Report 2's link to deliverables on sidebar and added extandable content for meeting notes 352.

**Comment by berfinsimsekk** [comment]
Please tick your name after reviewing your personal page.

- [ ] Ali Kaan
- [ ] Artun
- [ ] Hakan
- [ ] Yasir
- [ ] Alp Eren
- [ ] Aral
- [ ] Berk
- [ ] Bedirhan
- [X] Berfin
- [ ] İhsan Mert
- [ ] İrem
- [ ] Yusuf Erdem

**Comment by araldortogul** [comment]
I have updated my personal wiki page.

**Comment by LehabuL** [comment]
I also compelted my part, will will my weekly efforts also

**Comment by iremmer** [comment]
I also checked the necessary parts.

**Comment by aeren02** [comment]
I have updated my personal wiki page in accordance with my recent programming progress
