### ISSUE TITLE
 As a fresh eyes. provide feedback to improve repo 

### ISSUE THREAD

**Issue by ihsanmertatalay** [bounswe/bounswe2022group6#161]

**Comment by ihsanmertatalay** [comment]
Project may be summerize at Github homepage 
# Requirements
1. Users should confirm all delete operations

2. Users may have profile which list theirs posts

3. Users may go to the profile page of post owner.

4. Users may view profile of users.

5. Users may save post for reading later

6. Users may search posts by owner (writer) or search profile

**Comment by ihsanmertatalay** [comment]
added label

**Comment by yusuferdemnacar** [comment]
🙇‍♂️ @ihsanmertatalay, I would suggest reading the [issue creation guide](https://github.com/bounswe/bounswe2022group6/wiki/Issue-Creation-Guide) to help with creating more effective issues as well as keeping them uniform.

**Comment by ihsanmertatalay** [comment]
7. User may see list of last visited posts.
