### ISSUE TITLE
Requirements Review (1.1.1.7-1.1.2.2.4)

### ISSUE THREAD

**Issue by BPamukcuoglu** [bounswe/bounswe2022group6#163]
I’ve reviewed the requirements form 1.1.1.7 to 1.1.2.2.4 as we discussed at the meeting. I’ve founded a how statement at 1.1.1.7.1 which should be changed. Also, the rest of the section 1.1.1.7 relies on that how statement so those should be changed to. The rest of the requirements seemed ok to me.

Assigned @LehabuL to review and discuss.

**Comment by BPamukcuoglu** [comment]
Thanks, then leave the requirements of 1.1.1.7 section to the future customer meeting and see how it goes. For the 1.1.2.2.2 and 1.1.2.2.4 sections, I agree with you about adding those requirements. 

Thanks for your effort @LehabuL. 

I am closing the issue.

**Comment by yusuferdemnacar** [comment]
> * 1.1.2.2.2.6 Registered users shall be able to mark / unmark their posts as NSFW and blur / unblur the attached media.
> * 1.1.2.2.2.7 Registered users shall be able to mention / unmention other registered users in the description of their posts.

As we discussed in [meeting #3](https://github.com/bounswe/bounswe2022group6/wiki/Meeting-%233-18.10.2022), I'm separating these items into two as they describe related but different functionalities.

The new items are
* 1.1.2.2.2.6 Registered users shall be able to mark their SFW posts as NSFW and blur the attached media.
* 1.1.2.2.2.7 Registered users shall be able to unmark their NSFW posts as SFW and unblur the attached media.
* 1.1.2.2.2.8 Registered users shall be able to mention other registered users in the description of their posts.
* 1.1.2.2.2.9 Registered users shall be able to unmention other mentioned registered users in the description of their posts.
