### ISSUE TITLE
Reviewing the System requirements 1.2.2 to 1.2.5

### ISSUE THREAD

**Issue by mberkturgut** [bounswe/bounswe2022group6#164]
As decided in [Meeting #2](https://github.com/bounswe/bounswe2022group6/wiki/Meeting-%232-11.10.2022) we will review all requirements from [1.2.2](https://github.com/bounswe/bounswe2022group6/wiki/Requirements#122-forum) to [1.2.5](https://github.com/bounswe/bounswe2022group6/wiki/Requirements#125-notification) to ensure that they follow the standards discussed in the lecture. 

Deadline: 17.10.2022
Reviewer: @ihsanmertatalay

**Comment by mberkturgut** [comment]
I have reviewed the requirements and made the following changes:

Updated: 1.2.2.1.3, 1.2.2.3,2, 1.2.4.1
Added: 1.2.2.3.1

@ihsanmertatalay Can you please have a look when you are available? Thank you

**Comment by ihsanmertatalay** [comment]
I have reviewed this changes
Updated: 1.2.2.1.3, 1.2.2.3,2, 1.2.4.1
Added: 1.2.2.3.1
It is ok except a little opinion
1.2.2.3.1 A post preview shall consist of the title, #upvote, #comments, and the first 75 characters of the post as a brief.  
 May contain author
 @mberkturgut

**Comment by ihsanmertatalay** [comment]
I review requirements from [1.2.2] to [1.2.5]  I didn't want to change it because I didn't see a need.

**Comment by mberkturgut** [comment]
Thanks @ihsanmertatalay, then I am closing the issue. Feel free to reopen it in case you see any need for an update.

**Comment by mberkturgut** [comment]
@ihsanmertatalay Regarding your suggestion on 1.2.2.3.1 we discussed that we would have the author name, gender, age and post date/time in the post previews. I will update the requirements accordingly.

**Comment by mberkturgut** [comment]
I updated [1.2.2.3.1](https://github.com/bounswe/bounswe2022group6/wiki/Requirements#1223-post-previews), as well as making relevant adjustments on user registration 1.1.1.1.1. Feel free to reopen the issue in case you see any need for an update.
