### ISSUE TITLE
Reviewing the requirements 

### ISSUE THREAD

**Issue by berfinsimsekk** [bounswe/bounswe2022group6#165]
As decided in [Meeting #2](https://github.com/bounswe/bounswe2022group6/wiki/Meeting-%232-11.10.2022) we will review requirement [1.1.2.2.5](https://github.com/bounswe/bounswe2022group6/wiki/Requirements#11225-voting-a-post) and all requirements from [1.1.2.3.1](https://github.com/bounswe/bounswe2022group6/wiki/Requirements#11231-creating-a-comment) to [1.1.2.3.5](https://github.com/bounswe/bounswe2022group6/wiki/Requirements#11235-voting-a-comment) to ensure that they follow the standards discussed in the lecture.

Deadline: 17.10.2022

**Comment by berfinsimsekk** [comment]
I have reviewed the requirements and they seemed ok to me. @iremmer please review and let me know if anything is not ok to you.

**Comment by iremmer** [comment]
I reviewed the mentioned requirements and they seem fine to me too, thus, I am closing this issue.
