### ISSUE TITLE
Creating a Communication Plan for Frontend, Backend and Mobile Subteams

### ISSUE THREAD

**Issue by artun-akdogan** [bounswe/bounswe2022group6#166]
A communication plan should be created for regular development. A regular day and a communication platform should be decided for weekly communication for all groups. Those decisions should be reported on [Communication Plan](https://github.com/bounswe/bounswe2022group6/wiki/Communication-Plan) page.

Please tick when you complete that of your sub-team.
- [x] Frontend
- [x] Backend
- [x] Mobile

Deadline: 16.10.2022

**Comment by artun-akdogan** [comment]
Backend Group's communication plan has been updated on [Communication Plan](https://github.com/bounswe/bounswe2022group6/wiki/Communication-Plan) page.

**Comment by mberkturgut** [comment]
@artun-akdogan I updated the title to be more concise. Also I checked your addition to the [Communication Plan](https://github.com/bounswe/bounswe2022group6/wiki/Communication-Plan) page and it looks good. Lastly, it might be a good idea to assign this issue to one person from each subteam to ensure that they have created their own plans. Thank you!

**Comment by artun-akdogan** [comment]
@mberkturgut Thank you for the correction. Now, I have updated assignees to the first person that appeared on [Meeting #2](https://github.com/bounswe/bounswe2022group6/wiki/Meeting-%232-11.10.2022#1-team-formation) for each team.

**Comment by mberkturgut** [comment]
You're welcome! I reassigned to issue to myself to review it altogether after each plan is finished.

**Comment by aeren02** [comment]
I have edited the communication plan to add the Mobile Group's communication plan as Discord, for the reasons that were explained in [Issue #171](https://github.com/bounswe/bounswe2022group6/issues/171)

**Comment by mberkturgut** [comment]
@LehabuL Any updates on [this](https://github.com/bounswe/bounswe2022group6/wiki/Communication-Plan)?

**Comment by LehabuL** [comment]
Sorry for the delay, closing the issue.

**Comment by mberkturgut** [comment]
@LehabuL no problem, thank you
