### ISSUE TITLE
Reviewing the Requirement Sections 1.1.2.4 to 1.2.1

### ISSUE THREAD

**Issue by Aliqaan** [bounswe/bounswe2022group6#168]
As decided in [Meeting #2](https://github.com/bounswe/bounswe2022group6/wiki/Meeting-%232-11.10.2022), we will review the requirements from [1.1.2.4](https://github.com/bounswe/bounswe2022group6/wiki/Requirements#1124-label-management) to [1.2.1](https://github.com/bounswe/bounswe2022group6/wiki/Requirements#121-reputation-system) to ensure that they follow the standards discussed in the lecture.

Please comment any changes made to the requirements in the mentioned sections under this issue.

Deadline: 18.10.2022

**Comment by araldortogul** [comment]
I have checked the requirements from 1.1.2.4 until 1.2.1 and I have some suggestions:

### 1.1.2.4 Label Management:
This part looks alright, I don't think we need to change this part.

### 1.1.3.1 Messaging:
We can combine 1.1.3.1.1 and 1.1.3.1.2 into one requirement, like:
1.1.3.1.1 Registered users shall be able to send text or media messages to each other.

The requirement 1.1.3.1.3 seems a little ambiguous for me. We can rewrite it as:
1.1.3.1.2 Registered users shall be able to turn on/off their messaging feature.

1.1.3.1.4 and 1.1.3.1.5 can be combined to one single requirement:
1.1.3.1.3 Registered users shall be able to block/unblock other users.

Again, we can combine the requirements 1.1.3.1.6 and 1.1.3.1.7:
1.1.3.1.4 Registered users shall not be able to send a message to a user who has blocked them or turned off their messaging feature.

I believe that the requirement 1.1.3.1.8 is a design feature and can be erased completely.

### 1.1.3.2 Reporting

The requirements from 1.1.3.2.1 and 1.1.3.2.2 can be combined to a single requirement:
1.1.3.2.1 Registered users shall be able to report other registered users for spam or harassment.

Furthermore, we can also combine requirements from 1.1.3.2.3 until 1.1.3.2.5 to a single requirement:
1.1.3.2.2 Registered users shall be able to report posts or comments for misinformation, violating the app rules, or mislabeling.

1.1.3.2.6 doesn't need any change.

### 1.1.4 Interactions Between the Users and the Chatbot

In my opinion, the requirement "1.1.4.3 Users shall be able to acquire information from the chatbot depending on their answers to the questions asked by the chatbot." explains this section enough. We can erase 1.1.4.1 and 1.1.4.2.

### 1.2.1 Reputation System
Almost all of the requirements written for the reputation system explain the design features of it. I suggest that we should erase them and write:
1.2.1.1: Registered users shall have reputation scores which can increase or decrease by the upvotes/downvotes of their posts and comments.
1.2.1.2: Accounts with a certain amount of negative reputation shall be deleted by the system automatically (1.2.1.4)

**Comment by araldortogul** [comment]
I have changed 1.1.3.1.3, combined 1.1.3.1.4-1.1.3.1.5, deleted 1.1.3.1.8.
I have also deleted 1.2.1.1.

We will update the requirements about the ChatBot after discussing it with the group.

**Comment by araldortogul** [comment]
After discussing Chatbot requirements with the group, we have decided to delete 1.1.4.3.
I have deleted 1.1.4.3.
We can close the issue for now @Aliqaan

**Comment by Aliqaan** [comment]
Closing this issue now, feel free to open it if there is any suggestions.
