### ISSUE TITLE
Uploading the Backend Meeting #1 Notes

### ISSUE THREAD

**Issue by artun-akdogan** [bounswe/bounswe2022group6#169]
The notes for meeting 2 should be uploaded to the wiki.

Deadline: 19.10.2022

**Comment by artun-akdogan** [comment]
Meeting notes page has been created and the agenda has been uploaded [here](https://github.com/bounswe/bounswe2022group6/wiki/Backend-Meeting-%231-17.10.2022).

**Comment by artun-akdogan** [comment]
@mberkturgut thank you for uploading meeting notes. I have reviewed it and added few more points. Therefore, I am closing this issue now.

**Comment by mberkturgut** [comment]
Thanks @artun-akdogan for additions, it looks very comprehensive now. Thank you for the well-prepared agenda and moderating a super-efficient meeting as well :) Kudos to the backend team!
