### ISSUE TITLE
Doing research about Chatbot

### ISSUE THREAD

**Issue by LehabuL** [bounswe/bounswe2022group6#17]
We need to investigate how to integrate / implement Chatbot features. As stated in the project description _"You can develop your chatbot using Telegram’s Chatbot API."_, we can research Telegram and similar ones.

You can document your findings [here](https://github.com/bounswe/bounswe2022group6/wiki/Chatbot).

**Comment by yusuferdemnacar** [comment]
Reminder.

**Comment by LehabuL** [comment]
I completed the page, sorry for the delay. @araldortogul, @artun-akdogan you can populate the page if you found any other integration / services related to the Chatbot.
