### ISSUE TITLE
Deciding which programming language to use for mobile development

### ISSUE THREAD

**Issue by yasirdikbas** [bounswe/bounswe2022group6#173]
Each sub-team member should carry out some research about advantages and disadvantages of programming languages and frameworks for mobile development including but not limited to Java, Kotlin and Flutter. Then we will decide on which one to use by voting here.

**Comment by BPamukcuoglu** [comment]
Well I agree with you and believe that React Native will be the best fit for our requirements.

**Comment by yasirdikbas** [comment]
It seems as all of us are convinced that React Native will be the perfect choice for our mobile development. Hope everything will go as planned. I am closing the issue right now.
