### ISSUE TITLE
Implementing User Registration

### ISSUE THREAD

**Issue by artun-akdogan** [bounswe/bounswe2022group6#181]
User registration functionality should be implemented. The model that is used for users should be as follows:

* userID: An ID number as primary key
* username: Unique username, which only includes alphanumeric characters and '-'
* email: Unique email
* password_hash: Password that should be kept with sha256 hashing algorithm
* birth_date: Birth date of user
* gender: Gender choices for user

I also created a Django application for login, registration, and account management functionalities. The application in the src folder for protecting the structure.

**Deadline:** 27.11.2022

**Comment by yusuferdemnacar** [comment]
I created the User model in accmgr project. You can find the commit here: 6f276910ce470c14771893466974981acbeec270.

**Comment by yusuferdemnacar** [comment]
I added the registration view in accmgr app. You can find the commit here: 6fa5bc0b7d6cbc4f2cc647620f10e3191ac27b67.

**Comment by yusuferdemnacar** [comment]
I have not yet added the URL and did not return a proper response, but tested the database a bit. The app is able to create the User table successfully. The following needs to be done for now:

- [ ] Adding the view URL to the urls.py

- [ ] Adding a JSON response to the view

**Comment by artun-akdogan** [comment]
I have completed the tasks requested above, To call the new register function, one should post a request on /register/ URL. I also added a superuser to Django admin console for debugging purposes. Please note that I fixed errors that occurred while parsing data and increased database checks with overloading "save" function. Database did not enforced choice field of gender correctly.
The following should be considered further:

- [ ] Database checks should be increased
- [ ] JSON responses should be more detailed and should return the correct code

**Comment by artun-akdogan** [comment]
I also added testcases, and test_settings.py to be used only for testing in dockerfile with sqlite3, and without using .env file. As this file is only used on test with isolated environment, and replaced afterwards, it does not create security issues. Please refer to commits: 6103bf7db354282e6b894fefbb471e626a2cbf91, and 555796bc1c5347c77d38521366a2f4c63f80542b.

**Comment by yusuferdemnacar** [comment]
> * [x]  Database checks should be increased
> * [x]  JSON responses should be more detailed and should return the correct code

I have completed the tasks above. The database constraints are now checked properly before saving a user into the database. The signup endpoint now responds to the requests with proper responses.

I rewrote the unit tests to cover a broader range of cases as we discussed with @artun-akdogan.

I also wrote an API documentation for this endpoint in JSON format. You can easily use it in Postman. You can find the documentation [here](https://github.com/bounswe/bounswe2022group6/blob/Backend/Feature/Signup/Application/Backend/api_docs/signup_doc.json).

You can find the commits here;
* DB constraint checks - ecb0c2f9c2fc874ce2e85b7455b3bb8513c66ac5
* Detailed JSON responses - be363aaa15a3cf2fba9ccb7aaaa64075c8d52f50
* Unit tests - a9081707e8225b37325411fa6e7c14e44c6c739e, 2f65b264d65d7795540e44367c318f6fe0922c7b, 57dd42d04d973b101856756186028e79badb2260
* API documentation - 37c3ea7c4bbe9243d24fc89462c4b41fc056fdac
