### ISSUE TITLE
Removing Phone Number Signup and Login Options from Rquirements

### ISSUE THREAD

**Issue by yusuferdemnacar** [bounswe/bounswe2022group6#186]
As discussed in [meeting #4](), the user signup and authentication functionalities using the phone number should be removed.
The option to add the phone number to the profile should remain.

The reason for this removal is that sending SMS messages to users signing up is priced and we were explicitly asked NOT to use non-free tools for this course.

**Deadline:** 25.10.2022

**Comment by yusuferdemnacar** [comment]
> Reminder @yusuferdemnacar

Thanks for the reminder and sorry for the delay.

I changed items 1.1.1.1.1 and 1.1.1.2.1 in the requirements.

**Comment by mberkturgut** [comment]
@yusuferdemnacar I am reopening this issue as I belive reviewing the following three requirements including phone number is necessary:

- 1.1.1.4.1
- 1.1.1.4.2
- 1.1.1.6.1

Feel free to close the issue if you belive no change is required. Thank you for your effort!

**Comment by yusuferdemnacar** [comment]
Thanks, I took a look at the items mentioned but since they are not related to the signup and login functionalities, I did not change anything. I will bring this up in the next meeting.
