### ISSUE TITLE
Doing Research About W3C

### ISSUE THREAD

**Issue by BPamukcuoglu** [bounswe/bounswe2022group6#19]
We need to do research about w3c.

**Comment by Aliqaan** [comment]
I have created a page for our W3C research to fill with our findings. You can find the page [here](https://github.com/bounswe/bounswe2022group6/wiki/W3C).

**Comment by yusuferdemnacar** [comment]
The task is done, please reopen the issue to make changes.

**Comment by Aliqaan** [comment]
I have gathered some information and write a brief summary to [W3C](https://github.com/bounswe/bounswe2022group6/wiki/W3C).  Feel free to add anything or edit the content if you wish.
