### ISSUE TITLE
Editing the README.md file

### ISSUE THREAD

**Issue by yusuferdemnacar** [bounswe/bounswe2022group6#2]
Creation of a template for the readme file. The readme file should describe the work that this group will do throughout the semester.

**Comment by LehabuL** [comment]
Me and @mberkturgut finished creating the [README.md](https://github.com/bounswe/bounswe2022group6#cmpe-352-software-engineering-2022-spring---group-6). The file now contains basic information about the course and team members' & instructors github links. I am closing the issue but if you come up with an improvement please modify the file and leave a comment here.

**Comment by LehabuL** [comment]
I have added wiki page link to README.
