### ISSUE TITLE
Creating Base Pages for Mobile

### ISSUE THREAD

**Issue by araldortogul** [bounswe/bounswe2022group6#200]
The following pages should be created for Milestone 1.

- [x] Log in page
- [x] Sign up page
- [x] Home page
- [x] Error pages
- [x] Profile page

The pages do **not** need to be complete for now. It is sufficient if the pages can perform their simplest functions.

**Note:** The checks done while redirecting between pages will be implemented after the integration of mobile & backend framework. Until then, the page redirection can be done without any checks.

Deadline: 01.11.2022

Assignees: @aeren02, @araldortogul, @BPamukcuoglu, @yasirdikbas

**Comment by aeren02** [comment]
I have written the error pages and added example posts to the home page.
