### ISSUE TITLE
AWS EC2 instance creation and deployment

### ISSUE THREAD

**Issue by artun-akdogan** [bounswe/bounswe2022group6#208]
An amazon instance should be created and then deployed with latest build from GitHub, master branch.

Deadline: 31.10.2022

**Comment by BPamukcuoglu** [comment]
Instance created aws @artun-akdogan fyi

**Comment by artun-akdogan** [comment]
Docker containers have been created; however, both frontend and backend cannot work in single vanilla machine because of RAM requirements. Therefore, I have added swap memory to at least save the milestone.

**Comment by BPamukcuoglu** [comment]
I've tested it, works good enough. Thanks for your efforts 👍 💯

**Comment by yusuferdemnacar** [comment]
Since it is done, I am closing the issue, thanks.
