### ISSUE TITLE
Filling Basic User Requirements

### ISSUE THREAD

**Issue by LehabuL** [bounswe/bounswe2022group6#23]
I will add basic requirements such as registration, log-in etc. under [User Requirements](https://github.com/bounswe/bounswe2022group6/wiki/Requirements#11-user-requirements) in the [Requirements page](https://github.com/bounswe/bounswe2022group6/wiki/Requirements).

**Deadline:** 15/03/2021

Reviewer: @BPamukcuoglu

**Comment by LehabuL** [comment]
I added the related requirements. It consists of the following topics:

1. Registration
2. Doctor Verification
3. Account Management
4. Log in / Log out
5. Reset Password

We may introduce additional ones after the customer meeting session. @BPamukcuoglu can you review and confirm the current state so that we can close this issue?

**Comment by BPamukcuoglu** [comment]
Thanks for your work. It seems great!
