### ISSUE TITLE
Creating Scenarios and Mockups for Milestone I

### ISSUE THREAD

**Issue by yusuferdemnacar** [bounswe/bounswe2022group6#230]
New scenarios that will be included in both the deliverables of milestone I and the project demo should be created.
These scenarios should cover what we will display in the project demo.
Some comments on the scenarios by the customer:
* They should be realistic 
  * The scenarios should make use of realistic names 
  * They should describe real actions that could be taken using the app

From what we gathered during [Meeting #4 with the customer](https://github.com/bounswe/bounswe2022group6/wiki/Meeting-%234---25.10.2022), the scenarios need not make use of additional imagery as they will be used during the demo with the real app.
The customer described them as written scenarios.

**Deadline:** 1.11.2022

**Comment by iremmer** [comment]
The scenarios are created, you can check them from the sidebar of our wiki page.
