### ISSUE TITLE
Reporting Individual Contribution

### ISSUE THREAD

**Issue by yusuferdemnacar** [bounswe/bounswe2022group6#231]
Individual contributions towards the milestone I should be reported. The report should be written in markdown file format.
These reports should be structured as described in the [submission instruction pdf](https://moodle.boun.edu.tr/mod/resource/view.php?id=657245):

> * Member: Info about myself (name, group)
> * Responsibilities: Overall description of the responsibilities that are assigned to me
> * Main contributions: Overall description of my contributions to the project until Customer Milestone Presentation
>   *  Code related significant issues: My issues that contribute to the code base
> demonstrated during the demo
>   * Management related significant issues: My issues that contribute to the
> management of our software project
> Note that only the most-significant ones, we track all your issues separately.
> * Pull requests: My pull requests
> * Additional information: Further relevant information related to my contributions (optional)

**Responsibles**
- [x] [Artun Akdoğan](https://github.com/artun-akdogan)
- [x] [Hakan Balık](https://github.com/LehabuL)
- [x] [Ali Kaan Biber](https://github.com/Aliqaan)
- [ ] [Yasir Dikbaş](https://github.com/yasirdikbas)
- [x] [Aral Dörtoğul](https://github.com/araldortogul)
- [ ] [Ihsan Mert Atalay](https://github.com/ihsanmertatalay)
- [ ] [Alp Eren İnceoğlu](https://github.com/aeren)
- [x] [Yusuf Erdem Nacar](https://github.com/yusuferdemnacar)
- [ ] [Ramazan Bedirhan Pamukçuoğlu](https://github.com/BPamukcuoglu)
- [x] [Berfin Şimşek](https://github.com/berfinsimsekk)
- [ ] [Mustafa Berk Turgut](https://github.com/mberkturgut)
- [x] [Beyza İrem Urhan](https://github.com/iremmer)

**Deadline:** 1.11.2022 - 12.00

**Comment by araldortogul** [comment]
I have just added my individual contribution report. I might add more stuff to it until tomorrow noon.

**Comment by artun-akdogan** [comment]
I have added my individual contribution report. I will update it with some minor improvements.

**Comment by yusuferdemnacar** [comment]
The deadline for the individual report is past, so I'm closing thee issue.
