### ISSUE TITLE
Creating Milestone I Group Review Report

### ISSUE THREAD

**Issue by yusuferdemnacar** [bounswe/bounswe2022group6#232]
Group review report for milestone I should be created. The report should be written in markdown file format.
The report should be structured as described in the [submission instruction pdf](https://moodle.boun.edu.tr/mod/resource/view.php?id=657245) to include at least the following:

> 1. Executive Summary: Summary of the project status and any changes that are planned for
> moving forward.
> 2. List and status of deliverables.
> 3. Evaluation of the status of deliverables and their impact on your project plan.
> 4. Evaluation of tools and processes you have used to manage your team project.
> 5. The requirements addressed in this milestone.
> 6. Overall description of responsibilities that are assigned to each member.
> 7. A Summary of work performed by each team member (in tabular format)

This is a group responsibility and we will distribute the work after the next meeting.

**Deadline:** 4.11.2022

**Comment by araldortogul** [comment]
I have prepared the outline of the report and filled my parts.

**Comment by LehabuL** [comment]
Similar to #227, since we have submitted the report I am closing the issue.
