### ISSUE TITLE
Listing ChatBot requirements

### ISSUE THREAD

**Issue by BPamukcuoglu** [bounswe/bounswe2022group6#25]
Chatbot requirements of the project will be listed under [System Requirements](https://github.com/bounswe/bounswe2022group6/wiki/Requirements#12-system-requirements) of the [Functional Requirements](https://github.com/bounswe/bounswe2022group6/wiki/Requirements#1-functional-requirements) topic.

**Comment by BPamukcuoglu** [comment]
@LehabuL can you please check the ChatBot requirements to close the issue ? We may update it after the customer meeting.

**Comment by LehabuL** [comment]
@BPamukcuoglu , it seems good for now. We can populate it after clarifications are made by the customer in the customer meeting. I am just not sure about 1.2.2.1, maybe we can also discuss it within customer meeting. I am not closing the issue but changing the label to block since we need feedback on this.

**Comment by LehabuL** [comment]
As discussed in [Meeting 5](https://github.com/bounswe/bounswe2022group6/wiki/Meeting-%235-03.20.2022), we decided to use Chatbot for:
- Assistance for app related stuff.
- Illness detection using symptoms.

@BPamukcuoglu, please revise the necessary [Requirements](https://github.com/bounswe/bounswe2022group6/wiki/Requirements#12-system-requirements).

**Comment by LehabuL** [comment]
Reminder, @BPamukcuoglu

**Comment by yusuferdemnacar** [comment]
Chatbot requirements are done and reviewed. Please comment on any changes to the chatbot requirements under this issue.

**Comment by yusuferdemnacar** [comment]
I added some items to the [chatbot requirements](https://github.com/bounswe/bounswe2022group6/wiki/Requirements#125-chatbot) in order to clarify the topic further.
