### ISSUE TITLE
Designing a Logo for Medishare

### ISSUE THREAD

**Issue by araldortogul** [bounswe/bounswe2022group6#250]
Currently, our application Medishare does not have a logo. It would be nice to have a simple logo which we can use in our app. It would also be great to use it as the icon for our mobile app. Currently, the icon of the mobile app looks like this:

<img src="https://user-images.githubusercontent.com/73420291/199266752-dc82c9e5-50cd-4ba4-9532-dc4113299c37.png" height="600" />

If anyone would like to volunteer, they can assign themselves to this issue.

Deadline: 06.12.2022 (Customer Milestone 2)

**Comment by LehabuL** [comment]
I have created the following image, we can either go with it or use another one

![MediShare](https://user-images.githubusercontent.com/56560206/199772175-eeb0c321-9386-4b6a-a3d4-084ce239d5c4.png)

**Comment by araldortogul** [comment]
> I have created the following image, we can either go with it or use another one
> 
> ![MediShare](https://user-images.githubusercontent.com/56560206/199772175-eeb0c321-9386-4b6a-a3d4-084ce239d5c4.png)

Thanks @LehabuL for the image, now our app looks much better on Android screens: ☺️


<img src="https://user-images.githubusercontent.com/73420291/199789494-a9da7fa2-3c5a-4b79-95ec-ce3bf651c1fa.png" height="600" />
