### ISSUE TITLE
Implementing Edit Account

### ISSUE THREAD

**Issue by mberkturgut** [bounswe/bounswe2022group6#253]
This function is required by all requirements under 1.1.1.2, 1.1.1.3 and 1.1.1.4.

As decided in the backend team meeting, functionalities related to not yet implemented parts of account, post etc. will not be covered in this issue. These include 1.1.1.3.10-11 Notifications, 1.1.1.3.9 to 1.1.1.3.13 Messaging, 1.1.1.3.3 Profile Picture and 1.1.1.2.5-1.1.1.3.7-1.1.1.4-7 location.  

Deadline: 8.11.2022

**Comment by mberkturgut** [comment]
For the location field we had a conversation with @BPamukcuoglu in which we came up with the idea to get the locations from the user using [Geolocation API](https://ip-api.com/docs/api:json). For this, backend needs to store the data with the following parameters: city, district, full adress.

To retrive the location data from the users, frontend & mobile will implement a user permission checkbox that allows sending the location information for each post and occasionally (to be specified) for logins.

**Comment by yusuferdemnacar** [comment]
As of [backend meeting #6](https://github.com/bounswe/bounswe2022group6/wiki/Backend-Meeting-%236---18.11.2022), I will be taking over the task.

The new deadline for the task is 19.11.2022

**Comment by yusuferdemnacar** [comment]
The profile viewing endpoint is implemented, you can see the commit here, 3a178332a9670b5835061b5c91231d3c353262fc.

**Comment by yusuferdemnacar** [comment]
The profile editing functionality is implemented, you can see the commit here, b705cbb2cc5b9f0580ce490ee9f6c8dc75d7df15.

**Comment by yusuferdemnacar** [comment]
As commented in pull request #273, the implementation part is done, however, writing tests and API documentation tasks remain.

The deadline for the remaining tasks is 23.11.2022
