### ISSUE TITLE
Creating a scenario and mock-up about a user sharing a post about plastic surgery

### ISSUE THREAD

**Issue by yasirdikbas** [bounswe/bounswe2022group6#34]
Task Description: As decided on [meeting 5](https://github.com/bounswe/bounswe2022group6/wiki/Meeting-%235-03.20.2022#action-items), a persona, pre-conditions of the scenario, step by step actions and acceptance criteria regarding "plastic surgery post" will be created on [User Scenarios & Mockups](https://github.com/bounswe/bounswe2022group6/wiki/User-Scenarios-&-Mockups) page.

Task Deadline: 22.03.2022 23.00

**Comment by LehabuL** [comment]
I moved the document to a new page, you can access it using this [link](https://github.com/bounswe/bounswe2022group6/wiki/Scenario-%231:-Sharing-a-Post). For your information, @yasirdikbas, @araldortogul, @aeren02, @haticerk

**Comment by haticerk** [comment]
I added the mock-up about sharing a post to  [Scenario #1](https://github.com/bounswe/bounswe2022group6/wiki/Scenario-%231:-Sharing-a-Post ) page.
