### ISSUE TITLE
Creating a scenario and mock-up about chatbot usage for assistance

### ISSUE THREAD

**Issue by LehabuL** [bounswe/bounswe2022group6#35]
As decided on [meeting 5](https://github.com/bounswe/bounswe2022group6/wiki/Meeting-%235-03.20.2022#action-items), a persona, the pre-conditions of the scenerio, step by step actions actions and the acceptance criteria on Chatbot usage will be listed in [User Scenarios & Mockups](https://github.com/bounswe/bounswe2022group6/wiki/User-Scenarios-&-Mockups) page.

**Deadline:** 03.22.2022 - 23.00

**Comment by artun-akdogan** [comment]
An initial setup of the chatbot usage scenario has been created as ["Scenario #2: Using Chatbot"](https://github.com/bounswe/bounswe2022group6/wiki/User-Scenarios-&-Mockups#scenario-2-using-chatbot)

**Comment by LehabuL** [comment]
I moved the document to a new page, you can find it [here](https://github.com/bounswe/bounswe2022group6/wiki/Scenario-%232:-Using-Chatbot). For your information, @artun-akdogan, @iremmer, @Aliqaan

**Comment by LehabuL** [comment]
The task is completed, well done everyone.
