### ISSUE TITLE
Backend imageUrl Lower Case

### ISSUE THREAD

**Issue by BPamukcuoglu** [bounswe/bounswe2022group6#351]
related code:

_imageURL = _imageURL.strip().lower() if _imageURL is not None else None

from mobile side, the uploaded image links are case sensitive, can we save it as it is ?

**Comment by yusuferdemnacar** [comment]
I have fixed the bug. You can find the commit here, 3958009b906c7bdd4b00be2e9c9b6b3287003f72.
