### ISSUE TITLE
Project Plan should be updated

### ISSUE THREAD

**Issue by berfinsimsekk** [bounswe/bounswe2022group6#367]
We should update the project plan according to work done by each member and upload to our wiki.

Deadlime: 09.12.2022

**Comment by araldortogul** [comment]
I have updated the project plan for the mobile team.

**Comment by berfinsimsekk** [comment]
I have updated the project plan for the backend and frontend team. After updating the date column, we can upload it.

**Comment by araldortogul** [comment]
The new project plan is [here](https://github.com/bounswe/bounswe2022group6/blob/master/deliverables/projectplan-3.pdf). I am closing this issue for now.
