### ISSUE TITLE
Updating user roles in the Requirements Page

### ISSUE THREAD

**Issue by aeren02** [bounswe/bounswe2022group6#37]
As decided on [meeting 5](https://github.com/bounswe/bounswe2022group6/wiki/Meeting-%235-03.20.2022#action-items), User roles will be moved under [1.1 User Requirements](https://github.com/bounswe/bounswe2022group6/wiki/Requirements#11-user-requirements) and patient will be reworded as guest where there will be Registered and Guest ones.

**Deadline:** 03.23.2022 - 16.00

**Comment by mberkturgut** [comment]
I checked that 1.1.3 user types satisfies the decision taken as an action in the meeting, so I am closing this issue.
