### ISSUE TITLE
CMPE 451 Milestone 2 Customer Feedback

### ISSUE THREAD

**Issue by artun-akdogan** [bounswe/bounswe2022group6#386]
A customer feedback page on Wiki should be created. It should include the following topics: 
- [x] The Flow Of The Presentation
- [X] Suggestions Made
- [ ] Questions
- [x] Introduction line with Presenter's Names

Please note that adding missing points and fixing grammatical errors are always welcome.

<b>Deadline:</b> 25.12.2022

**Comment by artun-akdogan** [comment]
I have initialized the page, and added suggestions that were made by Suzan Hoca.

**Comment by artun-akdogan** [comment]
I have added relevant links to Home Wiki Page and to the Sidebar.

**Comment by artun-akdogan** [comment]
I have also written the date and introduction draft. Please find more on page [Customer Milestone 2](https://github.com/bounswe/bounswe2022group6/wiki/CMPE-451-Milestone-2-Customer-Feedback)

**Comment by LehabuL** [comment]
I added the flow of the presentation [here](https://github.com/bounswe/bounswe2022group6/wiki/CMPE-451-Milestone-2-Customer-Feedback#the-flow-of-the-presentation). As far as I remember there were no questions but suggestions which @artun-akdogan already mentioned therefore I am closign the issue.
