### ISSUE TITLE
Updating User Scenario #3 Page

### ISSUE THREAD

**Issue by araldortogul** [bounswe/bounswe2022group6#41]
The wiki page for [User Scenario 3: Reviewing a Post on the Forum](https://github.com/bounswe/bounswe2022group6/wiki/Scenario-%233:-Reviewing-a-Post-on-the-Forum) needs to be reviewed and updated.

Deadline: 03.04.2022

**Comment by berfinsimsekk** [comment]
I have updated [Acceptence Criteria](https://github.com/bounswe/bounswe2022group6/wiki/Scenario-%233:-Reviewing-a-Post-on-the-Forum#acceptance-criteria) according to changes decided in [Meeting #7](https://github.com/bounswe/bounswe2022group6/wiki/Meeting-%237---03.30.2022) about [Requirements page](https://github.com/bounswe/bounswe2022group6/wiki/Requirements).

**Comment by araldortogul** [comment]
I have also reviewed and updated the Scenario #3's wiki page. I have added the [Acceptance Criteria](https://github.com/bounswe/bounswe2022group6/wiki/Scenario-%233:-Reviewing-a-Post-on-the-Forum#acceptance-criteria)  by adding 1.1.1.6.3.
