### ISSUE TITLE
Reviewing the Requirements

### ISSUE THREAD

**Issue by iremmer** [bounswe/bounswe2022group6#42]
The requirements should be reviewed by each member and the necessary enhancements should be done such as removing the ambiguity, adding details, correcting grammar, etc.

**Deadline:** 03.04.2022 Sunday 23.59

Please tick the box next to your name after reviewing.

- [x] Ali Kaan Biber
- [x] Alp Eren İnceoğlu
- [x] Aral Dörtoğul
- [x] Artun Akdoğan
- [x] Bedirhan Pamukçuoğlu
- [x] Berfin Şimşek
- [x] Beyza İrem Urhan
- [x] Hakan Balık
- [x] Hatice Erk
- [x] Mustafa Berk Turgut
- [x] Yasir Dikbaş
- [x] Yusuf Erdem Nacar

**Comment by yusuferdemnacar** [comment]
I have reviewed the [requirements page](https://github.com/bounswe/bounswe2022group6/wiki/Requirements) and added a few things to the [chatbot requirements](https://github.com/bounswe/bounswe2022group6/wiki/Requirements#125-chatbot). Please see #25 for the changes.

**Comment by aeren02** [comment]
I have reviewed the [requirements page](https://github.com/bounswe/bounswe2022group6/wiki/Requirements) and changed the word "should" to "shall" in [1.2.7 Messaging](https://github.com/bounswe/bounswe2022group6/wiki/Requirements#127-messaging) for consistency.

**Comment by mberkturgut** [comment]
I have updated the requirements 1.2.6.2, 1.1.2.2.12, 1.1.2.2.15 and added "trending post" to Glossary.

**Comment by LehabuL** [comment]
I updated glossary such that the items are listed and did some rephrasing.

**Comment by yusuferdemnacar** [comment]
Me and @mberkturgut revised the [requirements page](https://github.com/bounswe/bounswe2022group6/wiki/Requirements) page again in accordance with the [customer meeting 3](https://github.com/bounswe/bounswe2022group6/wiki/Customer-Meeting-Feedback#week-3) and the feedback we got through slack.

**Comment by iremmer** [comment]
I reviewed the requirements and fixed some grammar mistakes and typos.

**Comment by araldortogul** [comment]
I have also reviewed the requirements page and proofread the bullet points.

**Comment by berfinsimsekk** [comment]
I have reviewed the requirements and added 1.1.1.3.11 & 1.1.1.3.12 requirements under [editing the information in an account](https://github.com/bounswe/bounswe2022group6/wiki/Requirements#1113-editing-the-information-in-an-account).

**Comment by araldortogul** [comment]
> I have also reviewed the requirements page and proofread the bullet points.

Erased "the title of a post" that was a copy paste typo in 1.1.2.2.4.2, 1.1.2.2.4.3, and 1.1.2.2.4.4.

**Comment by LehabuL** [comment]
I changed 1.2.1.4 - since it is not logical to ban users with low amount of negative reputation. I also rephrased 1.2.3.6, since it was not clear enough. Lastly I added and corrected some punctuations.

**Comment by LehabuL** [comment]
Added 1.1.1.6.4 Registered users shall be able to log out from the application.

**Comment by LehabuL** [comment]
- Added 1.1.2.3.4 Viewing a Comment, and moved  re-enumerated Voting a Comment as 1.1.2.3.5

**Comment by artun-akdogan** [comment]
Fixed minor grammar mistakes at 1.1.1.2, 1.1.1.3, 1.1.2.2, 1.1.2.3, 1.2.1.4, 1.2.2.3, and 1.2.3.6.
