### ISSUE TITLE
Special Review on ChatBot Requirements

### ISSUE THREAD

**Issue by BPamukcuoglu** [bounswe/bounswe2022group6#43]
I tried to clarify the ChatBot requirements in order to satisfy today's customer meeting requests. Can you please double-check ?

**Comment by yusuferdemnacar** [comment]
I reviewed your changes and also added some further clarification to the [chatbot requirements](https://github.com/bounswe/bounswe2022group6/wiki/Requirements#125-chatbot) as discussed in the customer meeting 3. Thank you. I am now closing the issue, please comment on any changes to the chatbot requirements on issue #25 without reopening it.
