### ISSUE TITLE
Creating 100 posts for the presentation

### ISSUE THREAD

**Issue by aeren02** [bounswe/bounswe2022group6#447]
Each assignee is supposed to add 50 posts which will cover a huge array of different uses, with different users and different types of comments.

Deadline: 27.12.22 12.45

**Comment by yasirdikbas** [comment]
I have checked advancements achieved and I think the app seems alive now. Thank you for your collaboration.

**Comment by aeren02** [comment]
Created 50 posts and many comments by the users: RickMarty, annieS, FreddyConnely, FatimahHiggins, KelsieCisneros, jaffaar18, alicemalice, VerityKelly, AnitaSnow, ZaidMcbride, AhmetBarut, StefekAdsila, ZdzislawaLinda, Tarquinius, alp.

**Comment by yasirdikbas** [comment]
Usernames I used are, Suheyl, Roger, Mike, Aleyna, Zeynep, Züleyha, Yasir, Nebati, Tayyip, Kemal, Leyla, Polat, Hasib and mahmood.
