### ISSUE TITLE
Creating Customer Meeting Feedback Page

### ISSUE THREAD

**Issue by LehabuL** [bounswe/bounswe2022group6#45]
The findings / answers / feedback received from the customer should be documenented for project planning.

There has been a total of 3 customer meetings yet so the page should contain questions and related answers for these questions. 

**Deadline:** 03.04.2022

**Comment by LehabuL** [comment]
We have gathered with @yusuferdemnacar and completed the first two week's questions and answers. You can find the page [here](https://github.com/bounswe/bounswe2022group6/wiki/Customer-Meeting-Feedback).

**Comment by yusuferdemnacar** [comment]
I added the week 3 customer meeting questions and answers to the page with the help of @LehabuL . I am now closing the issue, please comment on this issue for the following weeks without reopening the issue.
