### ISSUE TITLE
Preparing the Group Milestone Report

### ISSUE THREAD

**Issue by araldortogul** [bounswe/bounswe2022group6#452]
The group milestone report needs to be prepared.

**Deadline:** 02.01.2023 23:59

The report should have:
1. Executive summary
    - Provide a summary of your project status.
    - Explain the status of the deliverables.
    - Provide final release notes.
    - Describe any changes your team has made or planned based on previous milestones to improve development process, explain how those changes will impact your process.
    - Provide reflections related to your Final Milestone Demo including lessons learned.
    - Describe what could be done differently in the start of the project to finalize the project, explain with reasons.

2. Progress based on teamwork
    - A summary of work performed by each team member (in tabular format)
3. Status of the requirement
    - Provide progress according to requirements, being either not started, in progress, or completed.
4. API Endpoints
    - The API documentation
    - Link to the API
    - Three examples of API calls corresponding to core functionality of your application, with instructions to access the functionality. All information needed to perform the calls must be provided (i.e., required parameter values). In other words, they must be replicable. Postman collections may be shared.
5. User Interface / User Experience
    - For each user interface design, provide links to the code in the project repository.
    - Screenshots of all implemented Web and Mobile interfaces.
    - May use interfaces submitted earlier and append new interfaces.
6. Annotations
    - Describe the status of annotations in your project
7. Standards
    - Explain the work you have completed towards the application of the W3C standards and ontologies.
8. Scenarios
    - Provide a scenario that encompasses all core functionalities of your project. Describe in detail the work that has been completed related to the features necessary to realize this scenario using the application.

**Comment by LehabuL** [comment]
I will create the template for the report with necessary topics and tables.

**Comment by LehabuL** [comment]
I created the file [here](https://github.com/bounswe/bounswe2022group6/blob/master/deliverables/CMPE451_Customer_Presentation_Milestone_3.md).

**Comment by yusuferdemnacar** [comment]
I will write the executive summary, annotations and standard parts. I will also create separate issues and branches to better keep track of the tasks shortly.

**Comment by yusuferdemnacar** [comment]
I have created separate issues for the sections I have mentioned above. You can find them here;
* #455
* #456 
* #457

**Comment by yusuferdemnacar** [comment]
I have completed the annotations and standards parts, and all subsections of the executive summary part except the status of deliverables. I am waiting for everyone to finish to complete it.
