### ISSUE TITLE
Preparing the Project Artifacts

### ISSUE THREAD

**Issue by araldortogul** [bounswe/bounswe2022group6#453]
The project artifacts should be prepared.

**Deadline:** 02.03.2023 23:59

The project artifacts consist of:

1. Manuals
    - User Manual: Instructions for how to use the system.
    - System Manual: System requirements and installation instructions for the web and mobile application. Must include docker installation. For the mobile application also provide instructions for use with an emulator.
2. Software Requirement Specification (SRS)
3. Software Design Documents (using UML)
4. User scenarios and mockups
5. Project Plan
6. Unit Tests

**Comment by LehabuL** [comment]
I completed the UML and scenarios & mockups parts and they have been both merged to master.
