### ISSUE TITLE
Uploading Meeting Notes #7

### ISSUE THREAD

**Issue by yusuferdemnacar** [bounswe/bounswe2022group6#46]
The notes for the 7th meeting need to be documented.

The notes should be created in accordance with the [meeting notes template](https://github.com/bounswe/bounswe2022group6/wiki/Meeting-Notes-Template).

**Deadline:** 03.04.2022

**Comment by yusuferdemnacar** [comment]
I uploaded the notes. You can find them [here](https://github.com/bounswe/bounswe2022group6/wiki/Meeting-%237---03.30.2022). I also added the page to the sidebar.

**Comment by LehabuL** [comment]
I added link of this page to wiki home.
