### ISSUE TITLE
Updating User Scenario #1 Page

### ISSUE THREAD

**Issue by aeren02** [bounswe/bounswe2022group6#47]
The wiki page for [Scenario #1: Sharing a Post](https://github.com/bounswe/bounswe2022group6/wiki/Scenario-%231:-Sharing-a-Post) needs to be reviewed and updated in accordance to the changes decided in meeting #7 concerning the labeling part.

**Deadline:** 03.04.2022 - 23.59

**Comment by haticerk** [comment]
[Scenario #1](https://github.com/bounswe/bounswe2022group6/wiki/Scenario-%231:-Sharing-a-Post) is updated in accordance to the changes decided in meeting 7. Please review and let me know if something is missing @aeren02.

**Comment by aeren02** [comment]
I have reviewed [Scenario #1](https://github.com/bounswe/bounswe2022group6/wiki/Scenario-%231:-Sharing-a-Post) and found minor inconsistencies in [Actions](https://github.com/bounswe/bounswe2022group6/wiki/Scenario-%231:-Sharing-a-Post#actions) and [Acceptance Criteria](https://github.com/bounswe/bounswe2022group6/wiki/Scenario-%231:-Sharing-a-Post#acceptance-criteria). Please check these parts and update the previously mentioned parts if found necessary @haticerk.

**Comment by aeren02** [comment]
I have reviewed [Scenario #1](https://github.com/bounswe/bounswe2022group6/wiki/Scenario-%231:-Sharing-a-Post) and checked that the required changes have been done.
