### ISSUE TITLE
Updating User Scenario #2 Page

### ISSUE THREAD

**Issue by Aliqaan** [bounswe/bounswe2022group6#48]
The wiki page for [Scenario #2: Using Chatbot](https://github.com/bounswe/bounswe2022group6/wiki/Scenario-%232:-Using-Chatbot) should be reviewed and updated so that it follows the newly updated requirements.

**Comment by LehabuL** [comment]
Me and @Aliqaan gathered and first changed the mockup and uploaded it to related [page](https://github.com/bounswe/bounswe2022group6/wiki/Scenario-%232:-Using-Chatbot). We then updated the acceptance criteria based on the updates on the [requirements](https://github.com/bounswe/bounswe2022group6/wiki/Requirements).

There is also a work in progress on requirements page (check issue [#52](https://github.com/bounswe/bounswe2022group6/issues/52)), therefore we will add Account related requirements after it is done, if necessarry.

**Comment by yusuferdemnacar** [comment]
Thank you for mentioning, the work on the [requirements](https://github.com/bounswe/bounswe2022group6/wiki/Requirements) page is done, you can use it now.

**Comment by LehabuL** [comment]
I added new requirements and changed the enumeration of the existing ones (which have been changed due to the revisions on the requirements page). I am closing the issue since the work is done.
