### ISSUE TITLE
Editing the sidebar of the wiki page

### ISSUE THREAD

**Issue by yusuferdemnacar** [bounswe/bounswe2022group6#5]
The sidebar of the wiki should be deployed to include the following topics:
- Home
- Team Members' wiki pages
- Meeting Notes

**Deadline:**  06.03.2022

**Comment by yusuferdemnacar** [comment]
The sidebar of the wiki page is created accordingly. The issue is closed but if you have suggestions for the sidebar please leave a comment.

**Comment by LehabuL** [comment]
Since I created the [Repository Research](https://github.com/bounswe/bounswe2022group6/wiki/Repository-Research) page, i updated the sidebar accordingly.
