### ISSUE TITLE
Adding Notification Requirement to the Functional Requirements

### ISSUE THREAD

**Issue by mberkturgut** [bounswe/bounswe2022group6#50]
As decided in the [Meeting #8](), requirements related to doctors getting mobile notifications about posts that they might be interested to contribute will be added.

**Comment by mberkturgut** [comment]
Based on the case involved in [Scenerio #3](https://github.com/bounswe/bounswe2022group6/wiki/Scenario-%233:-Reviewing-a-Post-on-the-Forum), the relevant requirements are added, updaded and some of them are grouped under [1.2.9 - Notifications](https://github.com/bounswe/bounswe2022group6/wiki/Requirements#129-notifications)  is in the [Requirements](https://github.com/bounswe/bounswe2022group6/wiki/Requirements) page. This issue might be revisited in the future as updates about the notifications are considered.

All of the requirements that are affected:
1.2.9 and the requirements it includes
1.1.1.11
1.2.1.1.16
1.2.2.3

**Comment by yusuferdemnacar** [comment]
Thanks, @mberkturgut, I also added two more requirements, 1.2.9.3 and 1.2.9.4.

**Comment by mberkturgut** [comment]
Looking good! Thank you for notifying @yusuferdemnacar
