### ISSUE TITLE
Filling Account Operations Related Use Cases in the Use Case Diagram

### ISSUE THREAD

**Issue by LehabuL** [bounswe/bounswe2022group6#51]
I need to fill use cases related to account operations in the use case diagram which are:

- Create Account
- Edit Account
- Delete Account
- Log In
- Log out

**Deadline**: 03.04.2022
**Reviewer**: @yusuferdemnacar

**Comment by LehabuL** [comment]
I finished the task and @yusuferdemnacar reviewed it.

**Comment by yusuferdemnacar** [comment]
Thank you, @LehabuL, I reviewed the work, and it looks fine.
