### ISSUE TITLE
Fixing Requirements Categorization

### ISSUE THREAD

**Issue by yusuferdemnacar** [bounswe/bounswe2022group6#52]
The categorization of the [requirements](https://github.com/bounswe/bounswe2022group6/wiki/Requirements) should be fixed according to the feedback given.

* The requirements under the Account section of the system requirements should be migrated into the user requirements.
* The user requirements under the labels section of the system requirements should be migrated into the user requirements.

**Deadline:** 03.04.2022

**Comment by mberkturgut** [comment]
Thank you for your work! @yusuferdemnacar I reviewed it and made numbering adjustments. My suggestion is to reword the word "Label", specifying which label type it is in all occurances.

**Comment by yusuferdemnacar** [comment]
Thanks for the revision, nice suggestion, I will look into it later since it is not an emergency.
