### ISSUE TITLE
Filling Post and Comment Operations Related Use Cases in the Use Case Diagram

### ISSUE THREAD

**Issue by berfinsimsekk** [bounswe/bounswe2022group6#53]
We need to fill use cases related to post and comment operations in the use case diagram which are:

- Create Post
- Edit Post
- Delete Post
- Vote Post
- Report Post
- Create Comment
- Edit Comment
- Delete Comment
- Vote Comment
- Report Comment

Deadline: 03.04.2022

**Comment by iremmer** [comment]
We worked on the provided task and filled the diagram. Also took some notes on the diagram to discuss in the meeting in the evening.
