### ISSUE TITLE
Designing the Use Case Diagram

### ISSUE THREAD

**Issue by haticerk** [bounswe/bounswe2022group6#55]
Following tasks should be completed.

* Colorizing the diagram
* Adding new arrows between user-types and use cases
* Reviewing the final version of use-case diagram.   

**Deadline:** 05.04.2022

**Comment by berfinsimsekk** [comment]
I have colorized the cases layer by layer in order to identify them easily and reviewed the diagram.

**Comment by haticerk** [comment]
I added new arrows between user-types and use cases in accordance with the requirements. Also, I added a new case as "Verify Doctor" for admins. @berfinsimsekk please also review my work and close this issue if everything is okay.

**Comment by berfinsimsekk** [comment]
I have reviewed your work, everything is clear. Thanks.
