### ISSUE TITLE
Class Diagram: Creating a Class for Message

### ISSUE THREAD

**Issue by haticerk** [bounswe/bounswe2022group6#56]
The fields and functions of Message class should be specified.

This task should be reviewed by @artun-akdogan. 
**Deadline:** 04.04.2022 at 20.00

**Comment by haticerk** [comment]
I added the structure of Message class to chart we work on that.  @artun-akdogan please review and let me know if everything is okay.

**Comment by artun-akdogan** [comment]
I added readDate variable and related functions to let know the sender understand if the message has been read.
