### ISSUE TITLE
Class Diagram: Creating a Class for Post

### ISSUE THREAD

**Issue by berfinsimsekk** [bounswe/bounswe2022group6#57]
The fields and functions of Post class should be specified.

This task should be reviewed by @haticerk .
**Deadline:** 04.04.2022 at 20.00

**Comment by berfinsimsekk** [comment]
I added the structure of Post class to chart that we work on. @haticerk  please review and let me know if everything is okay.

**Comment by haticerk** [comment]
I reviewed the Post class, it looks great. You have clearly defined everything. Thank you!
