### ISSUE TITLE
Class Diagram: Creating a Class for Searchbar

### ISSUE THREAD

**Issue by artun-akdogan** [bounswe/bounswe2022group6#59]
The fields and functions of the Searchbar class should be specified.

This task should be reviewed by @Aliqaan
Deadline: 04.04.2022 at 20.00

**Comment by artun-akdogan** [comment]
Now, I've finished the structure of the Searchbar and PostPreview classes. @Aliqaan please review and let me know if anything should be updated/added.

**Comment by Aliqaan** [comment]
@artun-akdogan I review your work now and the Searchbar class looks great and comprehensive. Well done!

**Comment by artun-akdogan** [comment]
@Aliqaan Thank you for your review. I am closing this issue now as it has been completed.
