### ISSUE TITLE
Creating a page for the repository research

### ISSUE THREAD

**Issue by yusuferdemnacar** [bounswe/bounswe2022group6#6]
A page needs to be created to store the repositories that we liked. The page should have,
- repository names as headers that are also links to the repositories
- a brief explanation of what the repository is for
- a brief explanation to why the person who found it liked it
- the name of the team member who found it

**Deadline:** 06.03.2022

**Comment by LehabuL** [comment]
I have created the page. You can find it [here](https://github.com/bounswe/bounswe2022group6/wiki/Repository-Research). I also added 2 dummy paragraphs.

**Comment by yusuferdemnacar** [comment]
Since the page is created I am closing this issue.
