### ISSUE TITLE
Class Diagram: Creating a Class for Home Feed

### ISSUE THREAD

**Issue by yusuferdemnacar** [bounswe/bounswe2022group6#61]
The fields and functions of Home Feed class should be specified.

This task should be reviewed by @mberkturgut
**Deadline:** 04.04.2022 at 20.00

**Comment by yusuferdemnacar** [comment]
I have created the class for the Home Feed in the Class Diagram at Lucidchart. @mberkturgut can you review it?

**Comment by mberkturgut** [comment]
Dear @yusuferdemnacar , 
I reviewed your work on Lucid.app and it looks fine. So I am closing this issue.
Best regards,
