### ISSUE TITLE
Class Diagram: Creating a Class for Chat

### ISSUE THREAD

**Issue by aeren02** [bounswe/bounswe2022group6#62]
The fields and functions of Chat class should be specified.

This task should be reviewed by @araldortogul 
**Deadline:** 04.04.2022 at 20.00

**Comment by araldortogul** [comment]
Thanks you @aeren02 for your effort! I have checked out your work and it looks fine for now. It is worth discussing how the Chat class should interact with the other classes.
See you in the next meeting!
