### ISSUE TITLE
Class Diagram: Creating a Class for Report

### ISSUE THREAD

**Issue by aeren02** [bounswe/bounswe2022group6#63]
The fields and functions of the Report class should be specified.

This task should be reviewed by @aeren02 
**Deadline:** 04.05.2022 at 20.00

**Comment by yasirdikbas** [comment]
I roughly completed it, now waiting for @aeren02's review.

**Comment by aeren02** [comment]
I have reviewed the class and found a possible error where report() function doesn't return anything. This is incorrect notation, and furthermore I believe this function should return 'Report' similar to other declaration functions. After @yasirdikbas has looked into this, this issue can be closed
