### ISSUE TITLE
Class Diagram: Creating a Class for Notifications

### ISSUE THREAD

**Issue by mberkturgut** [bounswe/bounswe2022group6#65]
The fields and functions of the Notifications class should be specified.

This task should be reviewed by @LehabuL 
Deadline: 04.04.2022 at 20.00

**Comment by mberkturgut** [comment]
@LehabuL Can you please share your feedback for it? Thank you

**Comment by mberkturgut** [comment]
Feedback has been discussed and applied in the team meeting

**Comment by LehabuL** [comment]
We reviewed this part altogether with other ones. We also did the necessary updates.
