### ISSUE TITLE
Class Diagram: Creating a Class for Comments

### ISSUE THREAD

**Issue by BPamukcuoglu** [bounswe/bounswe2022group6#66]
The fields and functions of the Comments class should be specified.

This task should be reviewed by @iremmer 
Deadline: 04.04.2022 at 20.00

**Comment by iremmer** [comment]
I have a question regarding your specification:

- Why did you prefer "notificationID" to be a type of "String"?

**Comment by BPamukcuoglu** [comment]
To increase the number of data to prevent any overflow issues
