### ISSUE TITLE
Creating a Meeting Notes Template and Writing the First Meeting Notes

### ISSUE THREAD

**Issue by haticerk** [bounswe/bounswe2022group6#7]
A standard template which includes separate parts for agenda, discussion and action items should be determined for the meeting notes. Then, the first meeting notes should be documented on the wiki page.

**Comment by berfinsimsekk** [comment]
You can find the Meeting Notes Template [here.](https://github.com/bounswe/bounswe2022group6/wiki/Meeting-Notes-Template)

**Comment by yusuferdemnacar** [comment]
The sidebar now includes the template page.

**Comment by haticerk** [comment]
[Here](https://github.com/bounswe/bounswe2022group6/wiki/Meeting-Notes-%231) is the first meeting notes.
