### ISSUE TITLE
Sequence Diagram: Searchbar

### ISSUE THREAD

**Issue by artun-akdogan** [bounswe/bounswe2022group6#70]
The sequence diagram of the Searchbar should be designed.

@iremmer should review this task
Deadline: 09.04.2022

**Comment by artun-akdogan** [comment]
A draft of a sequence diagram of searchbar is now completed. @iremmer please review and notify me if anything should be added or updated.

**Comment by iremmer** [comment]
Thank you, I have reviewed your work and it is great.
