### ISSUE TITLE
Sequence Diagram: Report Content

### ISSUE THREAD

**Issue by BPamukcuoglu** [bounswe/bounswe2022group6#71]
The sequence diagram of Report Content process should be designed.

@Aliqaan  is the reviewer of this task.
Deadline: 09.04.2022

**Comment by yusuferdemnacar** [comment]
Quick comment: I have moved the lifeline of the report object such that it starts with the constructor.

**Comment by Aliqaan** [comment]
I have reviewed your work and it looks nice and informative. Good job!
