### ISSUE TITLE
Sequence Diagram: Admin Label Creation

### ISSUE THREAD

**Issue by Aliqaan** [bounswe/bounswe2022group6#75]
The sequence diagram of Admin Label Creation process should be designed.

@yasirdikbas is the reviewer of this task.
Deadline: 09.04.2022

**Comment by Aliqaan** [comment]
I have completed the sequence diagram of Admin Label Creation process and it now shows the alternative scenario when a label already exists in the system. @yasirdikbas can you review and tell if anything is unclear or should be updated?

**Comment by yasirdikbas** [comment]
As far as I've checked there seems to be no problem about the diagram, everything seems really good. I think you can close the issue.
