### ISSUE TITLE
The Sequence Diagram of "Post Edit" needs to be created 

### ISSUE THREAD

**Issue by yasirdikbas** [bounswe/bounswe2022group6#76]
The sequence diagram of "Post  Edit"  process should be designed.

@araldortogul is the reviewer of this task.
Deadline: 10.04.2022

**Comment by yasirdikbas** [comment]
I roughly completed the "Post Edit" diagram, can you please check and let me know if anything is missing in it @araldortogul ?

**Comment by araldortogul** [comment]
Thank you for your contribution, @yasirdikbas. The sequence diagram that you have prepared for editing a post looks great. You can close this issue.
