### ISSUE TITLE
Sequence Diagram: Notifications

### ISSUE THREAD

**Issue by mberkturgut** [bounswe/bounswe2022group6#77]
The sequence diagram of a notification creation process should be designed.

@aeren02 should review this task.

Deadline: 09.04.2022 @21:00

**Comment by mberkturgut** [comment]
I prepared the notification creation and showing it to doctor process for a recently created post with the help of @yusuferdemnacar

**Comment by aeren02** [comment]
I have reviewed your sequence diagram and I couldn't find any faults. Therefore, I'm now closing this issue.
