### ISSUE TITLE
Sequence Diagram: Vote a Post/Comment

### ISSUE THREAD

**Issue by araldortogul** [bounswe/bounswe2022group6#79]
The sequence diagram of Voting a Post/Comment process should be designed.

@BPamukcuoglu is the reviewer of this task.
Deadline: 09.04.2022

**Comment by araldortogul** [comment]
I have completed the sequence diagram of the "Vote Post/Comment" action.
@BPamukcuoglu you can review it and let me know if any updates should be done.

**Comment by BPamukcuoglu** [comment]
That look's fine, nice work 👍
