### ISSUE TITLE
RAM & Project Plan Design

### ISSUE THREAD

**Issue by berfinsimsekk** [bounswe/bounswe2022group6#82]
We should design RAM(responsibility assignment matrix) & Project Plan according to our completed issues. 

[Aral](https://github.com/bounswe/bounswe2022group6/wiki/Aral-D%C3%B6rto%C4%9Ful) and [Bedirhan](https://github.com/bounswe/bounswe2022group6/wiki/Bedirhan-Pamukcuoglu) are the reviewers of this task.
Deadline: 13.04.2022

**Comment by haticerk** [comment]
We created a template for both RAM and Project Plan. Now, we are waiting for group members to mark their work.

**Comment by berfinsimsekk** [comment]
Everybody has marked their work.

**Comment by berfinsimsekk** [comment]
We splitted the plan into to 2 parts one for cmpe352, the other for cmpe451 because of apperance purpose. Then we merged them into one pdf file.

**Comment by haticerk** [comment]
I uploaded project plan & RAM  to the repository.

**Comment by araldortogul** [comment]
I have reviewed the project plan & RAM, everything looks fine. @BPamukcuoglu can you also have a look at them?

**Comment by BPamukcuoglu** [comment]
Thanks to all of us, it looks great 🎉🎉 I am closing the issue
