### ISSUE TITLE
Writing Executive Summary and Evaluation of Tools Parts for the Milestone Report

### ISSUE THREAD

**Issue by yusuferdemnacar** [bounswe/bounswe2022group6#83]
The parts for the executive summary and evaluation of tools and processes that you have used to manage our project need to be written. The executive summary is the part where the status of the project and future changes that are planned are summarized. The evaluation part is where the tools and processes are evaluated and reported.

The executive summary part should summarize;
* What the project is
* What is the status of the project
* What we plan on doing moving forward as a team

The tool evaluation part should summarize;
* Which tools we have used
* What are the pros and cons of these tools
* How was our experience with these tools overall

**Deadline:** 13.04.2022 17.00

**Comment by yusuferdemnacar** [comment]
I have written the parts described on the shared Google Doc document for Milestone Report 1. It will be on the wiki page when the work is done.

**Comment by LehabuL** [comment]
I reviewed your work both for Executive Summary and Evaluation of Tools. I did some spacing and punctuation enhancements / corrections. I also did some minor rephrasings but overall it looks great, thanks for your efforts.
