### ISSUE TITLE
Uploading Deliverables to Wiki Page

### ISSUE THREAD

**Issue by aeren02** [bounswe/bounswe2022group6#89]
Deliverables should be prepared and ready to be uploaded to GitHub and to the document that's going to be submitted.

- [x] 1. @aeren02 should prepare deliverable 1.
- [x] 2. @Aliqaan should prepare deliverable 2.
- [x] 3. @LehabuL and @yusuferdemnacar should prepare deliverable 3.
- [x] 4. @berfinsimsekk and @haticerk should prepare deliverable 4.

**Deadline:** 15.04.2022-22.00

**Comment by Aliqaan** [comment]
I have prepared the wiki page for Deliverable 2. You can see the page [here](https://github.com/bounswe/bounswe2022group6/wiki/Deliverables:-D2).

**Comment by LehabuL** [comment]
We have finalized the class and sequence diagrams and uploaded both in addition to use case diagram. You can view them [here](https://github.com/bounswe/bounswe2022group6/wiki/D3:-Software-Design-Documents-in-UML).

**Comment by haticerk** [comment]
I uploaded project plan to repository as a pdf. There is [the link](https://github.com/bounswe/bounswe2022group6/blob/master/deliverables/projectplan.pdf). In the wiki page., I just uploaded the link. You can find [here](https://github.com/bounswe/bounswe2022group6/wiki/Project-Plan).

**Comment by berfinsimsekk** [comment]
I uploaded RAM to [wiki page](https://github.com/bounswe/bounswe2022group6/wiki/Project-Plan) as a png.

**Comment by berfinsimsekk** [comment]
I uploaded Project Plan to [wiki page](https://github.com/bounswe/bounswe2022group6/wiki/Project-Plan) as a png.
