### ISSUE TITLE
Enriching Label Types

### ISSUE THREAD

**Issue by LehabuL** [bounswe/bounswe2022group6#9]
There are only a few labels that Github offers to us. We need additional ones which will be beneficial throughout the project. Anyone can and encouraged to introduce new labels. As we discussed in the [meeting](https://github.com/bounswe/bounswe2022group6/wiki/Meeting-Notes-%231) @iremmer and @artun-akdogan are the main responsibles. You can comment down to show which labels you added and the reasoning. For further additions you can just edit your comment.

**Comment by yusuferdemnacar** [comment]
I added the label "Wiki" for the issues related to the content and layout of the wiki. So far we have used the "Documentation" label for this purpose, however, it does not accurately describe what we are doing. I also updated the labeling of the previous issues.

**Comment by haticerk** [comment]
I added priority related labels like high, medium and low. So that, they can be used to differentiate issues importance.

**Comment by LehabuL** [comment]
I added some labels to group issues by their state which are:

- Approved
- In Progress
- Blocked
- Completed

**Comment by yusuferdemnacar** [comment]
I added the label "Research" for the issues related to doing research. I also updated the labeling of the previous issues.

**Comment by yusuferdemnacar** [comment]
I made the following changes to the following labels to categorize them.
* Documentation &rarr; Type: Documentation
* Enhancement &rarr; Type: Enhancement
* Research &rarr; Type: Research
* Wiki &rarr; Type: Wiki
I also made their color the same to make it easier to see that they belong to the same category.

**Comment by yusuferdemnacar** [comment]
I am now closing this issue. Any addition to labels can be done by reopening this issue and commenting on the changes.
