### ISSUE TITLE
Completing Milestone Report's items  4 & 5

### ISSUE THREAD

**Issue by yasirdikbas** [bounswe/bounswe2022group6#90]
We need to complete Milestone Report's items 4&5 with @mberkturgut.
4. List and status of deliverables.
5. Evaluation of the status of deliverables and its impact on the project plan.
Deadline 15.04.2022, 22.00

**Comment by mberkturgut** [comment]
@yasirdikbas I reviewed your work for item 4. I did some ordering for the titles and made it compatible with the rest of the document. You can close this issue if you acknowledge.

**Comment by yasirdikbas** [comment]
Thank you for your review and help, I think now it is in a perfect state, so I am closing the issue.
