### ISSUE TITLE
Adding Deliverables to Wiki

### ISSUE THREAD

**Issue by aeren02** [bounswe/bounswe2022group6#91]
Individual wiki pages should be opened for each category and linked to each other accordingly. These pages should be reviewed by @haticerk and added to the sidebar by @aeren02.
Deadline: 04.15.2022-22.00

**Comment by LehabuL** [comment]
All of the deliverables except for Milestone is uploaded to wiki. I will close the issue as soon as it is also finalized and uploaded.

**Comment by LehabuL** [comment]
Milestone report 1 is uploaded [here](https://github.com/bounswe/bounswe2022group6/blob/master/deliverables/Milestone%20Report%201.pdf).
